# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chambo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: mozdag.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2D2B3E1AEC6B494EB4260655649E00ED }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C404461813FD4F24BAF3B4CEB7E49411 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mozdag.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2D2B3E1AEC6B494EB4260655649E00ED }}/chambometadata:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chambo'
          slot-name: 'Production'
          images: 'mozdag.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2D2B3E1AEC6B494EB4260655649E00ED }}/chambometadata:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D807E20D2A024146972D5180ED62411F }}